/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swing.crud;

import com.swing.util.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Faculty-1
 */
public class EditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form CreateEmployee
     */
    public EditEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        _name = new javax.swing.JTextField();
        _male = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        _female = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        _ssc = new javax.swing.JCheckBox();
        _hsc = new javax.swing.JCheckBox();
        _bsc = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        _address = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _remarks = new javax.swing.JTextArea();
        createEmployee = new javax.swing.JButton();
        resetEmployee = new javax.swing.JButton();
        empID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        _male.setText("Male");

        jLabel2.setText("Gender");

        _female.setText("Female");

        jLabel3.setText("Education");

        _ssc.setText("SSC");

        _hsc.setText("HSC");

        _bsc.setText("BSC");

        jLabel4.setText("Address");

        _address.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kakrail", "Banani", "Mirpur", "Gulshan" }));
        _address.setToolTipText("");

        jLabel5.setText("Remarks");

        _remarks.setColumns(20);
        _remarks.setRows(5);
        jScrollPane1.setViewportView(_remarks);

        createEmployee.setText("Update Employee");
        createEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeActionPerformed(evt);
            }
        });

        resetEmployee.setText("Reset");
        resetEmployee.setActionCommand("");

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empID)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(resetEmployee))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_male)
                        .addGap(57, 57, 57)
                        .addComponent(_female))
                    .addComponent(_name)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_ssc)
                        .addGap(31, 31, 31)
                        .addComponent(_hsc)
                        .addGap(33, 33, 33)
                        .addComponent(_bsc))
                    .addComponent(jScrollPane1)
                    .addComponent(_address, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_male)
                    .addComponent(_female))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_ssc)
                    .addComponent(_hsc)
                    .addComponent(_bsc))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployee)
                    .addComponent(resetEmployee))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeActionPerformed
        // TODO add your handling code here:
        updateEmployee(empID.getText());
    }//GEN-LAST:event_createEmployeeActionPerformed

    void updateEmployee(String code){
        String name = _name.getText();
        String gender = null;
        if(_male.isSelected()){
            gender = "Male";
        }
        if(_female.isSelected()){
            gender = "Female";
        }
        String education = "";
        if(_ssc.isSelected()){
            education += "SSC "; 
        }
        if(_hsc.isSelected()){
            education += "HSC ";
        }
        if(_bsc.isSelected()){
            education += "BSC";
        }
        String address = _address.getSelectedItem().toString();
        String remarks = _remarks.getText();
        //String output = name + "\n" + gender + "\n" + education + "\n" + address + "\n" + remarks;
        //JOptionPane.showMessageDialog(createEmployee, output);
        
        String sql = "update emp set name = ? , gender = ?, education = ?, address = ?, remarks = ? where code = ?";
        
        try {
            Connection con = DatabaseConnection.getDBConnection();
            PreparedStatement psmt = con.prepareStatement(sql);
            psmt.setString(1, name);
            psmt.setString(2, gender);
            psmt.setString(3, education);
            psmt.setString(4, address);
            psmt.setString(5, remarks);
            psmt.setString(6, code);
            int status = psmt.executeUpdate();
            JOptionPane.showMessageDialog(createEmployee, status);
 
        } catch (Exception e) {
            System.out.println(e);
        }
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String employeeID = empID.getText();
        editEmployee(employeeID);
    }//GEN-LAST:event_jButton1ActionPerformed

    void editEmployee(String code){
        String sql = "select * from emp where code = ?";
        
        try {
            Connection con = DatabaseConnection.getDBConnection();
            PreparedStatement psmt = con.prepareStatement(sql);
            psmt.setString(1, code);
            ResultSet rs = psmt.executeQuery();
            if(rs.next()){
                _name.setText(rs.getString("name"));
                if(rs.getString("gender").equals("Male")){
                    _male.setSelected(true);
                }else{
                    _female.setSelected(true);
                }

                _address.setSelectedItem(rs.getString("address"));
                _remarks.setText(rs.getString("remarks"));
                
                
            }else{
                JOptionPane.showMessageDialog(createEmployee, "Employee code doesn't match");
            }
            
            setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _address;
    private javax.swing.JCheckBox _bsc;
    private javax.swing.JRadioButton _female;
    private javax.swing.JCheckBox _hsc;
    private javax.swing.JRadioButton _male;
    private javax.swing.JTextField _name;
    private javax.swing.JTextArea _remarks;
    private javax.swing.JCheckBox _ssc;
    private javax.swing.JButton createEmployee;
    private javax.swing.JTextField empID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetEmployee;
    // End of variables declaration//GEN-END:variables
}
